### ISSUE TITLE
should support regexp matching of nic_tags

### ISSUE THREAD

**Issue by KodyKantor** [joyent/node-vmapi-resolver#2]
In some deployments nic_tags are going to vary slightly. Specifically in Manta and Triton deployments nic_tags used to look like:
- `admin`
- `manta`

But with rack-aware networking they look like:
- `admin_rack_[region]4_[rack_number]r`
- `manta_rack_[region]4_[rack_number]r`

The VMAPI resolver should be modified to search for nic_tags based on a regexp instead of exact string match.

**Comment by rmustacc** [comment]
On 8/22/18 8:49 , Kody A Kantor wrote:
> In some deployments nic_tags are going to vary slightly. Specifically in Manta and Triton deployments nic_tags used to look like:
> - `admin`
> - `manta`
> 
> But with rack-aware networking they look like:
> - `admin_rack_[region]4_[rack_number]r`
> - `manta_rack_[region]4_[rack_number]r`
> 
> The VMAPI resolver should be modified to search for nic_tags based on a regexp instead of exact string match.
> 

Seems worth noting this will be a major semantic change if we're not
changing the entry point, right?

**Comment by KodyKantor** [comment]
Sure. I think this would have unexpected behavior if the user of this library was already searching for VMs that had regex sensitive characters in the nictag names. So I suppose that merits a major version change.

**Comment by KodyKantor** [comment]
CR for this: https://cr.joyent.us/#/c/4733/

**Comment by KodyKantor** [comment]
Testing notes:
- I tested an updated version of this repo (with the CR change in it) in a pgstatsmon zone
- I manually edited the VMAPI entry for a Postgres VM to have it's nictag look like a RAN nictag
  - changed the VMAPI nictag from `manta` to `manta_rack_e50`
  - After this, RAN and non-RAN nictags were coexisting
- Verified that node-vmapi-resolver discovered the RAN Postgres instance and that pgstatsmon was able to connect to it

Full notes from those tests are in this gist:
https://gist.github.com/KodyKantor/ae9b4632e3abeb698f43f1caaf07c085

**Comment by KodyKantor** [comment]
added in 4acc2e5
